package com.cabletech.rms.proxy.dao.autoMapper;

import com.cabletech.rms.proxy.model.ApkDownloadHis;
import com.cabletech.rms.proxy.model.ApkDownloadHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApkDownloadHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    long countByExample(ApkDownloadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    int deleteByExample(ApkDownloadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    int insert(ApkDownloadHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    int insertSelective(ApkDownloadHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    List<ApkDownloadHis> selectByExample(ApkDownloadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ApkDownloadHis record, @Param("example") ApkDownloadHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    int updateByExample(@Param("record") ApkDownloadHis record, @Param("example") ApkDownloadHisExample example);
}