CREATE SEQUENCE IF NOT EXISTS SEQ_RELEASED_APPS START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_RELEASED_APK_VERSIONS START WITH 1;

CREATE TABLE IF NOT EXISTS RELEASED_APPS (
  ID          INT          NOT NULL PRIMARY KEY,
  APP_KEY     VARCHAR(128) NOT NULL UNIQUE,
  APP_NAME    VARCHAR(256),
  "DESC"      VARCHAR(512),
  CREATE_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RELEASED_APK_VERSIONS (
  ID           INT          NOT NULL PRIMARY KEY,
  APP_KEY      VARCHAR(128),
  VERSION_CODE INT          NOT NULL,
  VERSION_NAME VARCHAR(128) NOT NULL,
  FILE_NAME    VARCHAR(128) NOT NULL,
  FILE_PATH    VARCHAR(512) NOT NULL,
  FILE_SIZE    INT,
  UPLOADER     VARCHAR(32),
  "DESC"       VARCHAR(512),
  FORCE_UPDATE VARCHAR(8),
  UPLOADTIME   TIMESTAMP
);
--创建用户表       
CREATE TABLE IF NOT EXISTS RMS_USER (
  LOGIN_NAME VARCHAR(128) PRIMARY KEY,
  PASSWORD   VARCHAR(128)
);
--初始化用户 admin admin123
MERGE INTO RMS_USER (LOGIN_NAME, PASSWORD) KEY (LOGIN_NAME)
VALUES ('admin', 'd2e8e94d1fa9dc07880602387262439a00efd4a75cae42a10aec86ffa25ef64f');

CREATE TABLE IF NOT EXISTS apk_download_his (
  app_key       VARCHAR(128),
  apk_id        VARCHAR(128),
  download_time TIMESTAMP,
  download_ip   VARCHAR(128),
  download_imei VARCHAR(128)
);

