package com.cabletech.rms.proxy.model;

import java.util.Date;

public class ApkDownloadHis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APK_DOWNLOAD_HIS.APP_KEY
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    private String appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APK_DOWNLOAD_HIS.APK_ID
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    private String apkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APK_DOWNLOAD_HIS.DOWNLOAD_TIME
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    private Date downloadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APK_DOWNLOAD_HIS.DOWNLOAD_IP
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    private String downloadIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APK_DOWNLOAD_HIS.DOWNLOAD_IMEI
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    private String downloadImei;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APK_DOWNLOAD_HIS.APP_KEY
     *
     * @return the value of APK_DOWNLOAD_HIS.APP_KEY
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APK_DOWNLOAD_HIS.APP_KEY
     *
     * @param appKey the value for APK_DOWNLOAD_HIS.APP_KEY
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APK_DOWNLOAD_HIS.APK_ID
     *
     * @return the value of APK_DOWNLOAD_HIS.APK_ID
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public String getApkId() {
        return apkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APK_DOWNLOAD_HIS.APK_ID
     *
     * @param apkId the value for APK_DOWNLOAD_HIS.APK_ID
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setApkId(String apkId) {
        this.apkId = apkId == null ? null : apkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APK_DOWNLOAD_HIS.DOWNLOAD_TIME
     *
     * @return the value of APK_DOWNLOAD_HIS.DOWNLOAD_TIME
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public Date getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APK_DOWNLOAD_HIS.DOWNLOAD_TIME
     *
     * @param downloadTime the value for APK_DOWNLOAD_HIS.DOWNLOAD_TIME
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setDownloadTime(Date downloadTime) {
        this.downloadTime = downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APK_DOWNLOAD_HIS.DOWNLOAD_IP
     *
     * @return the value of APK_DOWNLOAD_HIS.DOWNLOAD_IP
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public String getDownloadIp() {
        return downloadIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APK_DOWNLOAD_HIS.DOWNLOAD_IP
     *
     * @param downloadIp the value for APK_DOWNLOAD_HIS.DOWNLOAD_IP
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setDownloadIp(String downloadIp) {
        this.downloadIp = downloadIp == null ? null : downloadIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APK_DOWNLOAD_HIS.DOWNLOAD_IMEI
     *
     * @return the value of APK_DOWNLOAD_HIS.DOWNLOAD_IMEI
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public String getDownloadImei() {
        return downloadImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APK_DOWNLOAD_HIS.DOWNLOAD_IMEI
     *
     * @param downloadImei the value for APK_DOWNLOAD_HIS.DOWNLOAD_IMEI
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setDownloadImei(String downloadImei) {
        this.downloadImei = downloadImei == null ? null : downloadImei.trim();
    }
}