package com.cabletech.rms.proxy.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApkDownloadHisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public ApkDownloadHisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppKeyIsNull() {
            addCriterion("APP_KEY is null");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNotNull() {
            addCriterion("APP_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andAppKeyEqualTo(String value) {
            addCriterion("APP_KEY =", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotEqualTo(String value) {
            addCriterion("APP_KEY <>", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThan(String value) {
            addCriterion("APP_KEY >", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThanOrEqualTo(String value) {
            addCriterion("APP_KEY >=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThan(String value) {
            addCriterion("APP_KEY <", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThanOrEqualTo(String value) {
            addCriterion("APP_KEY <=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLike(String value) {
            addCriterion("APP_KEY like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotLike(String value) {
            addCriterion("APP_KEY not like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyIn(List<String> values) {
            addCriterion("APP_KEY in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotIn(List<String> values) {
            addCriterion("APP_KEY not in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyBetween(String value1, String value2) {
            addCriterion("APP_KEY between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotBetween(String value1, String value2) {
            addCriterion("APP_KEY not between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andApkIdIsNull() {
            addCriterion("APK_ID is null");
            return (Criteria) this;
        }

        public Criteria andApkIdIsNotNull() {
            addCriterion("APK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApkIdEqualTo(String value) {
            addCriterion("APK_ID =", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdNotEqualTo(String value) {
            addCriterion("APK_ID <>", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdGreaterThan(String value) {
            addCriterion("APK_ID >", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdGreaterThanOrEqualTo(String value) {
            addCriterion("APK_ID >=", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdLessThan(String value) {
            addCriterion("APK_ID <", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdLessThanOrEqualTo(String value) {
            addCriterion("APK_ID <=", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdLike(String value) {
            addCriterion("APK_ID like", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdNotLike(String value) {
            addCriterion("APK_ID not like", value, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdIn(List<String> values) {
            addCriterion("APK_ID in", values, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdNotIn(List<String> values) {
            addCriterion("APK_ID not in", values, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdBetween(String value1, String value2) {
            addCriterion("APK_ID between", value1, value2, "apkId");
            return (Criteria) this;
        }

        public Criteria andApkIdNotBetween(String value1, String value2) {
            addCriterion("APK_ID not between", value1, value2, "apkId");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeIsNull() {
            addCriterion("DOWNLOAD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeIsNotNull() {
            addCriterion("DOWNLOAD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeEqualTo(Date value) {
            addCriterion("DOWNLOAD_TIME =", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeNotEqualTo(Date value) {
            addCriterion("DOWNLOAD_TIME <>", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeGreaterThan(Date value) {
            addCriterion("DOWNLOAD_TIME >", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DOWNLOAD_TIME >=", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeLessThan(Date value) {
            addCriterion("DOWNLOAD_TIME <", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeLessThanOrEqualTo(Date value) {
            addCriterion("DOWNLOAD_TIME <=", value, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeIn(List<Date> values) {
            addCriterion("DOWNLOAD_TIME in", values, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeNotIn(List<Date> values) {
            addCriterion("DOWNLOAD_TIME not in", values, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeBetween(Date value1, Date value2) {
            addCriterion("DOWNLOAD_TIME between", value1, value2, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadTimeNotBetween(Date value1, Date value2) {
            addCriterion("DOWNLOAD_TIME not between", value1, value2, "downloadTime");
            return (Criteria) this;
        }

        public Criteria andDownloadIpIsNull() {
            addCriterion("DOWNLOAD_IP is null");
            return (Criteria) this;
        }

        public Criteria andDownloadIpIsNotNull() {
            addCriterion("DOWNLOAD_IP is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadIpEqualTo(String value) {
            addCriterion("DOWNLOAD_IP =", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpNotEqualTo(String value) {
            addCriterion("DOWNLOAD_IP <>", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpGreaterThan(String value) {
            addCriterion("DOWNLOAD_IP >", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpGreaterThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_IP >=", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpLessThan(String value) {
            addCriterion("DOWNLOAD_IP <", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpLessThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_IP <=", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpLike(String value) {
            addCriterion("DOWNLOAD_IP like", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpNotLike(String value) {
            addCriterion("DOWNLOAD_IP not like", value, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpIn(List<String> values) {
            addCriterion("DOWNLOAD_IP in", values, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpNotIn(List<String> values) {
            addCriterion("DOWNLOAD_IP not in", values, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_IP between", value1, value2, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadIpNotBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_IP not between", value1, value2, "downloadIp");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiIsNull() {
            addCriterion("DOWNLOAD_IMEI is null");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiIsNotNull() {
            addCriterion("DOWNLOAD_IMEI is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiEqualTo(String value) {
            addCriterion("DOWNLOAD_IMEI =", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiNotEqualTo(String value) {
            addCriterion("DOWNLOAD_IMEI <>", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiGreaterThan(String value) {
            addCriterion("DOWNLOAD_IMEI >", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiGreaterThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_IMEI >=", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiLessThan(String value) {
            addCriterion("DOWNLOAD_IMEI <", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiLessThanOrEqualTo(String value) {
            addCriterion("DOWNLOAD_IMEI <=", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiLike(String value) {
            addCriterion("DOWNLOAD_IMEI like", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiNotLike(String value) {
            addCriterion("DOWNLOAD_IMEI not like", value, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiIn(List<String> values) {
            addCriterion("DOWNLOAD_IMEI in", values, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiNotIn(List<String> values) {
            addCriterion("DOWNLOAD_IMEI not in", values, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_IMEI between", value1, value2, "downloadImei");
            return (Criteria) this;
        }

        public Criteria andDownloadImeiNotBetween(String value1, String value2) {
            addCriterion("DOWNLOAD_IMEI not between", value1, value2, "downloadImei");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 20 13:54:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APK_DOWNLOAD_HIS
     *
     * @mbg.generated Tue Mar 20 13:54:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}